#!/bin/bash
#==========================================================================#
# zabbix6.2.sh - Instala zabbix 6.2, Grafana e Banco de dados no Debian 11
#
printf "+----------------------+\n"
printf "| %-20s | %-20s \n" "Baixando Repositório" ""
printf "+----------------------+\n"
#
wget https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-2%2Bdebian11_all.deb
#
printf "+------------------------+\n"
printf "| %-20s | %-20s \n" "Instalando Repositório" ""
printf "+------------------------+\n"
#
sudo dpkg -i zabbix-release_6.2-2+debian11_all.deb
#
printf "+----------------------------------+\n"
printf "| %-20s | %-20s \n" "Atualizando lista de Repositório" ""
printf "+----------------------------------+\n"
#
sudo apt update;
#
printf "+-----------------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Instalando o servidor, o frontend e o agente Zabbix" ""
printf "+-----------------------------------------------------+\n"
#
sudo apt install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent mariadb-server zabbix-get -y
#
printf "+-----------------------+\n"
printf "| %-20s | %-20s \n" "Starta mariadb" ""
printf "+-----------------------+\n"
#
sudo systemctl restart mariadb.service
#
printf "+---------------------+\n"
printf "| %-20s | %-20s \n" "Cria base de dados" ""
printf "+---------------------+\n"
#
sudo mysql -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"
#
printf "+------------------------------+\n"
printf "| %-20s | %-20s \n" "Cria usuário zabbix no banco" ""
printf "+------------------------------+\n"
#
sudo mysql -e "CREATE USER 'zabbix'@'localhost' IDENTIFIED BY 'zabbix';";
#
printf "+--------------------------------------+\n"
printf "| %-20s | %-20s \n" "Atribuir permissão do usuário zabbix" ""
printf "+--------------------------------------+\n"
#
sudo mysql -e "grant all privileges on zabbix.* to zabbix@localhost;";
#
printf "+---------------------------------+\n"
printf "| %-20s | %-20s \n" "Define função de criação de log" ""
printf "+---------------------------------+\n"
#
sudo mysql -e "set global log_bin_trust_function_creators = 1;";
#
printf "+----------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Popular o banco de dados com esquema inicial" ""
printf "+----------------------------------------------+\n"
#
sudo zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p"zabbix" zabbix;
#
printf "+----------------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Insere a senha no arquivo de conf do zabbix-server" ""
printf "+----------------------------------------------------+\n"
#
sudo sed 's/# DBPassword=/DBPassword=zabbix/g' /etc/zabbix/zabbix_server.conf -i;
#
printf "+---------------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Cópia arquivo que contém página inicial do zabbix" ""
printf "+---------------------------------------------------+\n"
#
cp zabbix.config.php /etc/zabbix/web/zabbix.conf.php
#
printf "+-------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Adiciona pacote de idioma no linux server" ""
printf "+-------------------------------------------+\n"
#
sed -i "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
#
printf "+------------------------+\n"
printf "| %-20s | %-20s \n" "Gera idioma adicionado" ""
printf "+------------------------+\n"
#
locale-gen
#
printf "+---------------------+\n"
printf "| %-20s | %-20s \n" "Reinicia serviços" ""
printf "+---------------------+\n"
#
sudo systemctl restart zabbix-server zabbix-agent apache2 mariadb.service 
#
printf "+-------------------------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Habilita para inicialização de serviços de forma automática" ""
printf "+-------------------------------------------------------------+\n"
#
sudo systemctl enable zabbix-server zabbix-agent apache2 mariadb.service
#
printf "+-----------------------------------+\n"
printf "| %-20s | %-20s \n" "Adiciona o repositório do Grafana" ""
printf "+-----------------------------------+\n"
#
sudo apt-get install -y gnupg2 curl
curl https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
#
printf "+-----------------------------+\n"
printf "| %-20s | %-20s \n" "Atualiza a lista de pacotes" ""
printf "+-----------------------------+\n"
#
sudo apt-get update
#
printf "+----------------------+\n"
printf "| %-20s | %-20s \n" "Instala o Grafana" ""
printf "+----------------------+\n"
#
sudo apt-get install -y grafana
#
printf "+------------------------------+\n"
printf "| %-20s | %-20s \n" "Iniciando serviço do Grafana" ""
printf "+------------------------------+\n"
#
sudo systemctl start grafana-server
#
printf "+------------------------------------------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Configura o serviço para iniciar automaticamente na inicialização do sistema" ""
printf "+------------------------------------------------------------------------------+\n"
#
sudo systemctl enable grafana-server
#
printf "+----------------------------------------+\n"
printf "| %-20s | %-20s \n" "Verifica se o serviço está em execução" ""
printf "+----------------------------------------+\n"
#
sudo systemctl status grafana-server
#
printf "+-----------------------------------------------+\n"
printf "| %-20s | %-20s \n" "Mostrar informações de login de Banco de dados" ""
printf "+-----------------------------------------------+\n"
echo "Mysql ou MariaDB"
echo "Usuário: root"
echo "Senha: $root_password"
echo "Banco de dados: localhost"
echo "Usuário: zabbix"
echo "Senha: zabbix"
#
printf "+----------------------------------------+\n"
printf "| %-20s | %-20s \n" "Mostrar informações de login de Zabbix" ""
printf "+----------------------------------------+\n"
echo "Zabbix"
echo "Acesse via navegador: http://<ip_do_servidor>/zabbix"
echo "Usuário: Admin"
echo "Senha: zabbix"
#
printf "+-----------------------------------------+\n"
printf "| %-20s | %-20s \n" "Mostrar informações de login de Grafana" ""
printf "+-----------------------------------------+\n"
echo "Grafana"
echo "Acesse via navegador: http://<ip_do_servidor>:3000"
echo "Usuário: admin"
echo "Senha: admin"
#
printf "+-------------------+\n"
printf "| %-20s | %-20s \n" "FIM DA INSTALAÇÃO" ""
printf "+-------------------+\n"
